server:
  port: 8081
spring:
  application:
    name: order-service
  security:
    oauth2:
      resourceserver:
        jwt.jwk-set-uri: http://localhost:8080/oauth2/jwks
  h2:
    console.enabled: false
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.springframework.security: TRACE