
server:
  port: 8082
spring:
  application:
    name: product-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/oauth2/jwks

logging:
  level:
    org.springframework.security: TRACE